### PR TITLE
[Ready for Review] Get library artist info

### LINKED ISSUE #1: Write endpoint for retrieving listener artists.
# Description

Get a sample of music metadata to support the initial homepage visualization.

# Plan

I am going to use the artists included in my [[last.fm](http://last.fm/)](http://last.fm) listening history. I will combine data from the music-brainz API with data from the spotify API to create the visualization. My artist history defines the sample size and is something I can verify and learn from.
To accomplish this, I will write a wrapper for the pylastFM that performs high level data operations. To start, I will:

- [x] initiate a class to handle data retrieval from LastFM.
- [x] write a method for retrieving the artists from some user.
- [x] write method to retrieve artist data from LastFM.

### PR DESCRIPTION
**Pull request by carterwward**
# Description
Resolves #1 
Initializes a python class to handle interacting with the LastFM API to retrieve, format, and write music data.
The two methods added here are to retrieve artists in a LastFM user's library and retrieval of artist information.
# Testing
Create a virtual environment with `python -m venv venv`. Install requirements with `pip install -r requirements.txt`. Run `python test.py`.

### CODE REVIEW

**Comment by rafarrel** [comment]
@carterwward Got this error when running test.py:

```
EE
======================================================================
ERROR: testGetArtistInfo (tests.lastfm_requests_test.LastFMConnectionTests.testGetArtistInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gcfar\Dev\lastFM-data-collection\tests\lastfm_requests_test.py", line 23, in testGetArtistInfo
    (list(artist_info["artist"].keys())),
          ~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: testLibraryArtists (tests.lastfm_requests_test.LastFMConnectionTests.testLibraryArtists)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gcfar\Dev\lastFM-data-collection\tests\lastfm_requests_test.py", line 18, in testLibraryArtists
    self.assertEqual(len(cardoor_libary_artists["artists"]["artist"]), 10)
                         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

----------------------------------------------------------------------
Ran 2 tests in 0.208s

FAILED (errors=2)
```

**Comment by carterwward** [comment]
> @carterwward Got this error when running test.py:
> 
> ```
> EE
> ======================================================================
> ERROR: testGetArtistInfo (tests.lastfm_requests_test.LastFMConnectionTests.testGetArtistInfo)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\Users\gcfar\Dev\lastFM-data-collection\tests\lastfm_requests_test.py", line 23, in testGetArtistInfo
>     (list(artist_info["artist"].keys())),
>           ~~~~~~~~~~~^^^^^^^^^^
> TypeError: 'NoneType' object is not subscriptable
> 
> ======================================================================
> ERROR: testLibraryArtists (tests.lastfm_requests_test.LastFMConnectionTests.testLibraryArtists)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\Users\gcfar\Dev\lastFM-data-collection\tests\lastfm_requests_test.py", line 18, in testLibraryArtists
>     self.assertEqual(len(cardoor_libary_artists["artists"]["artist"]), 10)
>                          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
> TypeError: 'NoneType' object is not subscriptable
> 
> ----------------------------------------------------------------------
> Ran 2 tests in 0.208s
> 
> FAILED (errors=2)
> ```

Seems like requests were unsuccessful

**Comment by rafarrel** [comment]
I thought it was going to be because I didn't put the API keys in, but I still got the error after doing that. So yeah, it looks like the requests aren't succeeding. Is it still working for you?

**Comment by carterwward** [comment]
> I thought it was going to be because I didn't put the API keys in, but I still got the error after doing that. So yeah, it looks like the requests aren't succeeding. Is it still working for you?

It is, want to hop in a voice chat real quick?

**Comment by rafarrel** [comment]
Figured out the problem. It's because I had a brainfart and put the API keys in the code instead of setting them as environment variables lol.

**Comment by carterwward** [comment]
> Figured out the problem. It's because I had a brainfart and put the API keys in the code instead of setting them as environment variables lol.

Good problem to have, no refactor!

**Comment by rafarrel** [comment]
To avoid this issue in the future when we set up CI/CD, let's see if we can do this programmatically in the test itself. To do this, we can either set the environment variable like it is now, but with OS or something like that. Or, we could switch it so it uses something called the keychain, which is nice because then you don't have to restart the machine for it to take effect. The choice is yours, what do you think?

**Comment by carterwward** [comment]
> To avoid this issue in the future when we set up CI/CD, let's see if we can do this programmatically in the test itself. To do this, we can either set the environment variable like it is now, but with OS or something like that. Or, we could switch it so it uses something called the keychain, which is nice because then you don't have to restart the machine for it to take effect. The choice is yours, what do you think?

I'm hesitant to upload the .env file to the repo for security reasons. Honestly I think short of having it be a secret within the CI/CD pipeline then this is probably as simple as possible as is since it just requires you to have the file in the directory.

**Pull request merged**
